<?php
require __DIR__.'/bootstrap.php'; installSchema();
$q=trim($_GET['q']??'');$type=$_GET['type']??'';$where=[];$args=[];
if($q!==''){$where[]='(o.item LIKE ? OR o.details LIKE ? OR m.message LIKE ? OR m.player LIKE ?)';$args=array_merge($args,array_fill(0,4,"%$q%"));}
if(in_array($type,['buy','sell','trade'],true)){$where[]='o.trade_type=?';$args[]=$type;}
$sql='SELECT o.*,m.player,m.message,m.source,m.posted_at FROM offers o JOIN messages m ON m.id=o.message_id'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY datetime(m.posted_at) DESC,o.id DESC LIMIT 300';
$st=db()->prepare($sql);$st->execute($args);$rows=$st->fetchAll();
$stats=db()->query("SELECT (SELECT COUNT(*) FROM messages) messages,COUNT(*) offers,SUM(trade_type='buy') buys,SUM(trade_type='sell') sells,COUNT(DISTINCT item_key) items,SUM(confidence<0.8) review FROM offers")->fetch();
$opps=db()->query("SELECT item,item_key,MAX(CASE WHEN trade_type='buy' THEN unit_price_ecto END) best_buy,MIN(CASE WHEN trade_type='sell' THEN unit_price_ecto END) best_sell,COUNT(*) samples FROM offers WHERE unit_price_ecto IS NOT NULL AND confidence>=0.8 AND COALESCE(price_basis,'') NOT IN ('bundle','currency_exchange') GROUP BY item_key HAVING best_buy IS NOT NULL AND best_sell IS NOT NULL AND best_buy>best_sell ORDER BY (best_buy-best_sell) DESC LIMIT 20")->fetchAll();
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LittyWatch</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#0b1020;color:#e5e7eb}.wrap{max-width:1500px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.muted{color:#94a3b8}.btn{display:inline-block;padding:10px 14px;border-radius:9px;background:#2563eb;color:#fff;text-decoration:none;border:0}.grid{display:grid;grid-template-columns:repeat(6,1fr);gap:12px;margin:20px 0}.card{background:#141b2d;border:1px solid #27324a;border-radius:14px;padding:18px}.num{font-size:27px;font-weight:750}.layout{display:grid;grid-template-columns:minmax(340px,1fr) minmax(600px,2fr);gap:16px}.filters{display:flex;gap:8px;flex-wrap:wrap}input,select{background:#0b1220;color:#e5e7eb;border:1px solid #334155;padding:10px;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #27324a;vertical-align:top}th{color:#93c5fd;position:sticky;top:0;background:#141b2d}.badge{padding:3px 7px;border-radius:20px;font-size:12px}.buy{background:#064e3b}.sell{background:#7f1d1d}.trade{background:#78350f}.scroll{max-height:760px;overflow:auto}.profit{color:#6ee7b7;font-weight:700}.loss{color:#fca5a5}.detail{color:#c4b5fd}.confidence{font-size:11px;color:#64748b}@media(max-width:950px){.grid{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div><h1 style="margin:0">LittyWatch</h1><div class="muted">Parser v0.4 — betere aantallen, bundels en variantprijzen</div></div><div><a class="btn" href="collect.php">Nu ophalen</a> <a class="btn" href="reparse.php">Bestaande data opnieuw parseren</a></div></div>
<div class="grid"><div class="card"><div class="muted">Berichten</div><div class="num"><?= (int)$stats['messages']?></div></div><div class="card"><div class="muted">Aanbiedingen</div><div class="num"><?= (int)$stats['offers']?></div></div><div class="card"><div class="muted">WTB</div><div class="num"><?= (int)$stats['buys']?></div></div><div class="card"><div class="muted">WTS</div><div class="num"><?= (int)$stats['sells']?></div></div><div class="card"><div class="muted">Items</div><div class="num"><?= (int)$stats['items']?></div></div><div class="card"><div class="muted">Te controleren</div><div class="num"><?= (int)$stats['review']?></div></div></div>
<div class="layout"><section class="card"><h2>Flip-kansen</h2><p class="muted">Alleen herkenningen met hoge zekerheid en een prijs per item.</p><div class="scroll"><table><thead><tr><th>Item</th><th>WTS</th><th>WTB</th><th>Marge</th></tr></thead><tbody><?php foreach($opps as $o):$spread=$o['best_buy']-$o['best_sell'];?><tr><td><?=h($o['item'])?><br><span class="muted"><?= (int)$o['samples']?> samples</span></td><td><?=number_format((float)$o['best_sell'],2)?>e</td><td><?=number_format((float)$o['best_buy'],2)?>e</td><td class="<?=$spread>0?'profit':'loss'?>"><?=number_format($spread,2)?>e</td></tr><?php endforeach;?><?php if(!$opps):?><tr><td colspan="4" class="muted">Nog onvoldoende vergelijkbare WTB/WTS-prijzen.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card"><div class="top"><h2>Herkende aanbiedingen</h2><form class="filters"><input name="q" value="<?=h($q)?>" placeholder="Zoek item, speler of tekst"><select name="type"><option value="">Alles</option><option value="buy" <?=$type==='buy'?'selected':''?>>WTB</option><option value="sell" <?=$type==='sell'?'selected':''?>>WTS</option><option value="trade" <?=$type==='trade'?'selected':''?>>WTT</option></select><button class="btn">Zoeken</button></form></div><div class="scroll"><table><thead><tr><th>Type</th><th>Item</th><th>Prijs</th><th>Speler / origineel</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><span class="badge <?=h($r['trade_type'])?>"><?=strtoupper(h($r['trade_type']))?></span></td><td><strong><?=h($r['item'])?></strong><?php if($r['details']):?><br><span class="detail"><?=h($r['details'])?></span><?php endif;?><br><span class="confidence"><?=round((float)$r['confidence']*100)?>% herkenning<?= $r['price_basis']?' · '.h($r['price_basis']):''?></span></td><td><?= $r['price_amount']!==null?h((string)$r['price_amount']).h($r['price_currency']):'-'?><?php if($r['quantity']):?><br><span class="muted">aantal: <?=h((string)$r['quantity'])?></span><?php endif;?><?php if($r['unit_price_ecto']!==null):?><br><span class="muted"><?=number_format((float)$r['unit_price_ecto'],2)?>e per stuk</span><?php endif;?></td><td><?=h($r['player'])?><?php if(!empty($r['raw_segment']) && trim($r['raw_segment'])!==trim($r['message'])):?><br><span class="detail">↳ <?=h($r['raw_segment'])?></span><?php endif;?><br><span class="muted"><?=h($r['message'])?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="4">Nog geen aanbiedingen. Klik op opnieuw parseren.</td></tr><?php endif;?></tbody></table></div></section></div></div></body></html>
