<?php
require __DIR__.'/bootstrap.php';
try { installSchema(); } catch(Throwable $e) { http_response_code(500); die('<h1>Installatiefout</h1><pre>'.h($e->getMessage()).'</pre>'); }
$q=trim($_GET['q']??''); $type=$_GET['type']??'';
$where=[];$args=[];
if($q!==''){$where[]='(message LIKE ? OR item LIKE ? OR player LIKE ?)';$args=array_merge($args,["%$q%","%$q%","%$q%"]);}
if(in_array($type,['buy','sell','trade'],true)){$where[]='trade_type=?';$args[]=$type;}
$sql='SELECT * FROM messages'.($where?' WHERE '.implode(' AND ',$where):'').' ORDER BY datetime(posted_at) DESC,id DESC LIMIT 200';
$st=db()->prepare($sql);$st->execute($args);$rows=$st->fetchAll();
$stats=db()->query("SELECT COUNT(*) total, SUM(CASE WHEN trade_type='buy' THEN 1 ELSE 0 END) buys, SUM(CASE WHEN trade_type='sell' THEN 1 ELSE 0 END) sells, COUNT(DISTINCT item) items FROM messages")->fetch();
$opps=db()->query("SELECT item, MAX(CASE WHEN trade_type='buy' THEN price_ecto END) best_buy, MIN(CASE WHEN trade_type='sell' THEN price_ecto END) best_sell, COUNT(*) samples FROM messages WHERE item IS NOT NULL AND price_ecto IS NOT NULL AND datetime(collected_at) >= datetime('now','-7 days') GROUP BY item HAVING best_buy IS NOT NULL AND best_sell IS NOT NULL ORDER BY (best_buy-best_sell) DESC LIMIT 20")->fetchAll();
?><!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>GW1 Market Scanner</title><style>
:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui;background:#0b1020;color:#e5e7eb}.wrap{max-width:1400px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;gap:16px;flex-wrap:wrap}.brand h1{margin:0;font-size:28px}.muted{color:#94a3b8}.btn{display:inline-block;padding:10px 14px;border-radius:9px;background:#2563eb;color:white;text-decoration:none;border:0}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:20px 0}.card{background:#141b2d;border:1px solid #27324a;border-radius:14px;padding:18px}.num{font-size:28px;font-weight:750;margin-top:5px}.layout{display:grid;grid-template-columns:1fr 2fr;gap:16px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:14px}input,select{background:#0b1220;color:#e5e7eb;border:1px solid #334155;padding:10px;border-radius:8px}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #27324a;vertical-align:top}th{color:#93c5fd;position:sticky;top:0;background:#141b2d}.badge{padding:3px 7px;border-radius:20px;font-size:12px}.buy{background:#064e3b}.sell{background:#7f1d1d}.trade{background:#78350f}.scroll{max-height:720px;overflow:auto}.profit{color:#6ee7b7;font-weight:700}.loss{color:#fca5a5}@media(max-width:900px){.grid{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:520px){.grid{grid-template-columns:1fr}}
</style></head><body><div class="wrap"><div class="top"><div class="brand"><h1>GW1 Market Scanner</h1><div class="muted">Testbare PHP/SQLite MVP</div></div><div><a class="btn" href="collect.php">Nu ophalen</a></div></div>
<div class="grid"><div class="card"><div class="muted">Berichten</div><div class="num"><?= (int)$stats['total'] ?></div></div><div class="card"><div class="muted">WTB</div><div class="num"><?= (int)$stats['buys'] ?></div></div><div class="card"><div class="muted">WTS</div><div class="num"><?= (int)$stats['sells'] ?></div></div><div class="card"><div class="muted">Items</div><div class="num"><?= (int)$stats['items'] ?></div></div></div>
<div class="layout"><section class="card"><h2>Flip-kansen</h2><p class="muted">Op basis van expliciete prijzen uit de laatste 7 dagen. Een advertentie is geen bevestigde verkoop.</p><div class="scroll"><table><thead><tr><th>Item</th><th>WTS</th><th>WTB</th><th>Marge</th></tr></thead><tbody><?php foreach($opps as $o):$spread=$o['best_buy']-$o['best_sell'];?><tr><td><?=h($o['item'])?><br><span class="muted"><?= (int)$o['samples']?> samples</span></td><td><?=number_format((float)$o['best_sell'],1)?>e</td><td><?=number_format((float)$o['best_buy'],1)?>e</td><td class="<?=$spread>0?'profit':'loss'?>"><?=number_format($spread,1)?>e</td></tr><?php endforeach;?><?php if(!$opps):?><tr><td colspan="4" class="muted">Nog onvoldoende geprijsde buy- én selloffers.</td></tr><?php endif;?></tbody></table></div></section>
<section class="card"><div class="top"><h2>Live aanbiedingen</h2><form class="filters"><input name="q" value="<?=h($q)?>" placeholder="Zoek item, speler of tekst"><select name="type"><option value="">Alles</option><option value="buy" <?=$type==='buy'?'selected':''?>>WTB</option><option value="sell" <?=$type==='sell'?'selected':''?>>WTS</option><option value="trade" <?=$type==='trade'?'selected':''?>>WTT</option></select><button class="btn">Zoeken</button></form></div><div class="scroll"><table><thead><tr><th>Type</th><th>Item / bericht</th><th>Prijs</th><th>Speler</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><span class="badge <?=h($r['trade_type'])?>"><?=strtoupper(h($r['trade_type']??'-'))?></span></td><td><strong><?=h($r['item']??'Onbekend')?></strong><br><span class="muted"><?=h($r['message'])?></span></td><td><?= $r['price_amount']!==null ? h((string)$r['price_amount']).h($r['price_currency']) : '-' ?></td><td><?=h($r['player'])?><br><span class="muted"><?=h($r['source'])?></span></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="4">Nog geen data. Klik op <strong>Nu ophalen</strong>.</td></tr><?php endif;?></tbody></table></div></section></div></div></body></html>
