<?php

declare(strict_types=1);

require __DIR__ . '/app/V2/Database.php';
require __DIR__ . '/app/V2/Intelligence/Schema.php';
require __DIR__ . '/app/V2/Intelligence/CurrencyFormatter.php';
require __DIR__ . '/app/V2/Intelligence/MarketExplorerService.php';

use LittyWatch\V2\Database;
use LittyWatch\V2\Intelligence\CurrencyFormatter;
use LittyWatch\V2\Intelligence\MarketExplorerService;

$pdo = Database::connect(__DIR__);
$service = new MarketExplorerService($pdo);
$money = new CurrencyFormatter(__DIR__);
$filters = [
    'q' => $_GET['q'] ?? '',
    'sort' => $_GET['sort'] ?? 'activity',
    'side' => $_GET['side'] ?? '',
    'confidence' => $_GET['confidence'] ?? 0,
    'liquidity' => $_GET['liquidity'] ?? 0,
];
$rows = $service->search($filters, 200);
$counts = $service->counts();
function h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function selected(string $a, string $b): string { return $a === $b ? ' selected' : ''; }
function scoreClass(int $score): string { return $score >= 75 ? 'good' : ($score >= 45 ? 'mid' : 'low'); }
?>
<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>LittyWatch V2.3 Marktverkenner</title>
<style>
:root{color-scheme:dark;--bg:#090c11;--panel:#121823;--panel2:#18202d;--line:#293547;--text:#edf1f7;--muted:#9ba8ba;--gold:#dab86d;--green:#68d9a3;--red:#ef9090;--orange:#e8b66f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#192335 0,#090c11 42%);color:var(--text);font:14px/1.45 Inter,system-ui,sans-serif}.wrap{max-width:1500px;margin:auto;padding:28px}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.eyebrow{color:var(--gold);font-size:11px;font-weight:900;letter-spacing:.16em}.top h1{font-size:32px;margin:3px 0}.muted{color:var(--muted)}a{color:inherit;text-decoration:none}nav a{color:var(--muted);margin-left:14px}nav a:hover{color:var(--gold)}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:22px 0}.card,.panel{background:rgba(18,24,35,.95);border:1px solid var(--line);border-radius:15px}.card{padding:16px}.card small{color:var(--muted)}.card strong{font-size:25px;display:block;margin-top:5px}.filters{display:grid;grid-template-columns:2fr repeat(4,minmax(130px,1fr)) auto;gap:10px;padding:15px;margin-bottom:16px}.filters input,.filters select,.filters button{width:100%;border:1px solid var(--line);border-radius:9px;background:#0e141d;color:var(--text);padding:10px 11px}.filters button{background:linear-gradient(135deg,#745c2c,#b58c45);font-weight:800;cursor:pointer}.panel{overflow:hidden}.table{overflow:auto}.row{min-width:1100px;display:grid;grid-template-columns:minmax(260px,2fr) 120px 120px 100px 90px 110px 110px 70px;gap:12px;align-items:center;padding:12px 16px;border-bottom:1px solid rgba(41,53,71,.75)}.row.header{font-size:11px;text-transform:uppercase;color:var(--muted);font-weight:900}.row:last-child{border-bottom:0}.item strong{font-size:15px}.item code{display:block;color:var(--muted);font-size:11px;max-width:420px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.price strong{display:block}.price small{color:var(--muted)}.badge{display:inline-flex;padding:5px 8px;border-radius:999px;font-weight:800;font-size:11px;background:#263142}.good{color:var(--green);background:rgba(104,217,163,.12)}.mid{color:var(--orange);background:rgba(232,182,111,.12)}.low{color:var(--red);background:rgba(239,144,144,.12)}.star{color:var(--gold);font-size:17px}.empty{padding:30px;color:var(--muted)}@media(max-width:950px){.stats{grid-template-columns:1fr 1fr}.filters{grid-template-columns:1fr 1fr}.top{flex-direction:column}}@media(max-width:560px){.wrap{padding:17px}.filters{grid-template-columns:1fr}}
</style></head><body><main class="wrap"><header class="top"><div><div class="eyebrow">LITTYWATCH V2.3</div><h1>Marktverkenner</h1><div class="muted">Zoek en filter alle berekende marktvarianten.</div></div><nav><a href="/v2.php">Dashboard</a><a href="/v2-intelligence.php">Intelligence</a><a href="/v2-watchlist.php">Watchlist</a><a href="/v2-trends.php">Trends</a></nav></header>
<section class="stats"><article class="card"><small>Markten</small><strong><?= $counts['markets'] ?></strong></article><article class="card"><small>Tweezijdige markt</small><strong><?= $counts['two_sided'] ?></strong></article><article class="card"><small>Deal score ≥ 60</small><strong><?= $counts['deals'] ?></strong></article><article class="card"><small>Hoge zekerheid</small><strong><?= $counts['high_confidence'] ?></strong></article></section>
<form class="panel filters" method="get"><input name="q" value="<?= h($filters['q']) ?>" placeholder="Zoek item of market key"><select name="sort"><option value="activity"<?= selected((string)$filters['sort'],'activity') ?>>Nieuwste</option><option value="deal"<?= selected((string)$filters['sort'],'deal') ?>>Beste deals</option><option value="liquidity"<?= selected((string)$filters['sort'],'liquidity') ?>>Liquiditeit</option><option value="confidence"<?= selected((string)$filters['sort'],'confidence') ?>>Zekerheid</option><option value="demand"<?= selected((string)$filters['sort'],'demand') ?>>Meeste vraag</option><option value="supply"<?= selected((string)$filters['sort'],'supply') ?>>Meeste aanbod</option><option value="item"<?= selected((string)$filters['sort'],'item') ?>>Itemnaam</option></select><select name="side"><option value=""<?= selected((string)$filters['side'],'') ?>>Alle markten</option><option value="both"<?= selected((string)$filters['side'],'both') ?>>WTB én WTS</option><option value="buy"<?= selected((string)$filters['side'],'buy') ?>>Met WTB</option><option value="sell"<?= selected((string)$filters['side'],'sell') ?>>Met WTS</option></select><select name="confidence"><option value="0">Alle zekerheid</option><option value="50"<?= selected((string)$filters['confidence'],'50') ?>>≥ 50%</option><option value="70"<?= selected((string)$filters['confidence'],'70') ?>>≥ 70%</option><option value="85"<?= selected((string)$filters['confidence'],'85') ?>>≥ 85%</option></select><select name="liquidity"><option value="0">Alle liquiditeit</option><option value="45"<?= selected((string)$filters['liquidity'],'45') ?>>Gemiddeld+</option><option value="75"<?= selected((string)$filters['liquidity'],'75') ?>>Hoog</option></select><button>Filteren</button></form>
<section class="panel"><div class="table"><div class="row header"><span>Markt</span><span>Mediaan WTB</span><span>Mediaan WTS</span><span>Spread</span><span>Deal</span><span>Zekerheid</span><span>Liquiditeit</span><span>Volgen</span></div><?php if(!$rows): ?><div class="empty">Geen markten gevonden met deze filters.</div><?php endif; ?><?php foreach($rows as $r): $spread=$r['spread_ecto']!==null?(float)$r['spread_ecto']:null; ?><a class="row" href="/v2-market.php?key=<?= rawurlencode((string)$r['market_key']) ?>"><div class="item"><strong><?= h($r['item']) ?></strong><code><?= h($r['market_key']) ?></code></div><div class="price"><strong><?= h($money->ecto($r['median_wtb_ecto']!==null?(float)$r['median_wtb_ecto']:null)) ?></strong><small><?= h($money->armbrace($r['median_wtb_ecto']!==null?(float)$r['median_wtb_ecto']:null)) ?></small></div><div class="price"><strong><?= h($money->ecto($r['median_wts_ecto']!==null?(float)$r['median_wts_ecto']:null)) ?></strong><small><?= h($money->armbrace($r['median_wts_ecto']!==null?(float)$r['median_wts_ecto']:null)) ?></small></div><div class="<?= $spread!==null&&$spread>=0?'good':'low' ?> badge"><?= $spread===null?'—':h($money->ecto($spread)) ?></div><div><strong><?= (int)$r['deal_score'] ?></strong>/100</div><div><span class="badge <?= scoreClass((int)$r['confidence_score']) ?>"><?= (int)$r['confidence_score'] ?>%</span></div><div><span class="badge <?= scoreClass((int)$r['liquidity_score']) ?>"><?= h($r['liquidity_label']) ?></span></div><div class="star"><?= (int)$r['watched']===1?'★':'☆' ?></div></a><?php endforeach; ?></div></section></main></body></html>
