<?php

declare(strict_types=1);

require __DIR__ . '/app/V2/Database.php';
require __DIR__ . '/app/V2/Intelligence/Schema.php';
require __DIR__ . '/app/V2/Intelligence/CurrencyFormatter.php';
require __DIR__ . '/app/V2/Intelligence/MarketExplorerService.php';

use LittyWatch\V2\Database;
use LittyWatch\V2\Intelligence\CurrencyFormatter;
use LittyWatch\V2\Intelligence\MarketExplorerService;

$pdo = Database::connect(__DIR__);
$service = new MarketExplorerService($pdo);
$money = new CurrencyFormatter(__DIR__);
$key = trim((string)($_GET['key'] ?? $_POST['market_key'] ?? ''));
if ($key === '') { http_response_code(400); exit('market_key ontbreekt.'); }
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (isset($_POST['unwatch'])) { $service->removeWatch($key); }
    else { $service->addWatch($key, (string)($_POST['label'] ?? '')); }
    header('Location: /v2-market.php?key=' . rawurlencode($key)); exit;
}
$market = $service->detail($key);
if ($market === null) { http_response_code(404); exit('Markt niet gevonden. Herbereken eerst V2 intelligence.'); }
$offers = $service->offers($key, 150);
$history = $service->history($key, 30);
function h(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function badgeClass(int $s): string { return $s>=75?'good':($s>=45?'mid':'low'); }
function mods(mixed $json): string { $d=json_decode((string)$json,true); return is_array($d)&&$d!==[]?implode(' · ',array_map('strval',$d)):'—'; }
$chart = array_map(static fn(array $r): array => ['t'=>$r['captured_at'],'b'=>$r['median_wtb_ecto']!==null?(float)$r['median_wtb_ecto']:null,'s'=>$r['median_wts_ecto']!==null?(float)$r['median_wts_ecto']:null], $history);
?>
<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?= h($market['item']) ?> — LittyWatch</title><style>
:root{color-scheme:dark;--bg:#090c11;--panel:#121823;--panel2:#18202d;--line:#293547;--text:#edf1f7;--muted:#9ba8ba;--gold:#dab86d;--green:#68d9a3;--red:#ef9090;--orange:#e8b66f}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 15% 0,#192335 0,#090c11 42%);color:var(--text);font:14px/1.45 Inter,system-ui,sans-serif}.wrap{max-width:1450px;margin:auto;padding:28px}a{color:var(--gold);text-decoration:none}.top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.eyebrow{font-size:11px;letter-spacing:.16em;color:var(--gold);font-weight:900}.top h1{font-size:31px;margin:3px 0}.muted{color:var(--muted)}.actions{display:flex;gap:8px;align-items:center}.button,input{border:1px solid var(--line);border-radius:9px;background:var(--panel2);color:var(--text);padding:10px 12px}.button{cursor:pointer}.primary{background:linear-gradient(135deg,#745c2c,#b58c45)}.stats{display:grid;grid-template-columns:repeat(6,1fr);gap:11px;margin:22px 0}.card,.panel{background:rgba(18,24,35,.95);border:1px solid var(--line);border-radius:15px}.card{padding:15px}.card small{color:var(--muted)}.card strong{font-size:22px;display:block;margin-top:4px}.good{color:var(--green)}.mid{color:var(--orange)}.low{color:var(--red)}.layout{display:grid;grid-template-columns:1.4fr .8fr;gap:16px}.panel{overflow:hidden}.panel h2{font-size:17px;margin:0;padding:16px;border-bottom:1px solid var(--line)}.chart{height:300px;padding:18px}.chart svg{width:100%;height:100%;overflow:visible}.legend{padding:0 18px 16px;color:var(--muted)}.offers{overflow:auto}.row{min-width:950px;display:grid;grid-template-columns:70px minmax(210px,1.5fr) 105px 100px 110px minmax(200px,2fr);gap:12px;padding:12px 16px;align-items:center;border-bottom:1px solid rgba(41,53,71,.75)}.row.header{font-size:11px;color:var(--muted);text-transform:uppercase;font-weight:900}.buy{color:var(--green);font-weight:900}.sell{color:var(--red);font-weight:900}.badge{display:inline-flex;padding:5px 8px;background:#263142;border-radius:999px;font-size:11px}.meta{padding:16px}.meta dl{margin:0;display:grid;grid-template-columns:140px 1fr;gap:9px}.meta dt{color:var(--muted)}.empty{padding:22px;color:var(--muted)}@media(max-width:1050px){.stats{grid-template-columns:repeat(3,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:600px){.wrap{padding:17px}.stats{grid-template-columns:1fr 1fr}.top{flex-direction:column}.actions{flex-wrap:wrap}}
</style></head><body><main class="wrap"><header class="top"><div><div class="eyebrow">MARKTINTELLIGENCE</div><h1><?= h($market['item']) ?></h1><div class="muted"><code><?= h($market['market_key']) ?></code></div></div><div class="actions"><a class="button" href="/v2-markets.php">← Markten</a><form method="post"><input type="hidden" name="market_key" value="<?= h($key) ?>"><?php if((int)$market['watched']===1): ?><button class="button" name="unwatch" value="1">★ Volgend</button><?php else: ?><input name="label" value="<?= h($market['item']) ?>" hidden><button class="button primary">☆ Watchlist</button><?php endif; ?></form></div></header>
<section class="stats"><article class="card"><small>Beste WTB</small><strong class="good"><?= h($money->ecto($market['best_wtb_ecto']!==null?(float)$market['best_wtb_ecto']:null)) ?></strong><span class="muted"><?= h($money->armbrace($market['best_wtb_ecto']!==null?(float)$market['best_wtb_ecto']:null)) ?></span></article><article class="card"><small>Beste WTS</small><strong class="low"><?= h($money->ecto($market['best_wts_ecto']!==null?(float)$market['best_wts_ecto']:null)) ?></strong><span class="muted"><?= h($money->armbrace($market['best_wts_ecto']!==null?(float)$market['best_wts_ecto']:null)) ?></span></article><article class="card"><small>Spread</small><strong><?= h($money->ecto($market['spread_ecto']!==null?(float)$market['spread_ecto']:null)) ?></strong></article><article class="card"><small>Deal score</small><strong><?= (int)$market['deal_score'] ?>/100</strong></article><article class="card"><small>Zekerheid</small><strong class="<?= badgeClass((int)$market['confidence_score']) ?>"><?= (int)$market['confidence_score'] ?>%</strong></article><article class="card"><small>Liquiditeit</small><strong class="<?= badgeClass((int)$market['liquidity_score']) ?>"><?= h($market['liquidity_label']) ?></strong></article></section>
<div class="layout"><section class="panel"><h2>Prijsontwikkeling — 30 dagen</h2><div class="chart"><svg id="chart" viewBox="0 0 900 260" preserveAspectRatio="none"></svg></div><div class="legend">Groen: mediaan WTB · Rood: mediaan WTS · <?= count($history) ?> snapshots</div></section><aside class="panel"><h2>Marktprofiel</h2><div class="meta"><dl><dt>Vraag</dt><dd><?= h($market['demand_label']) ?> (<?= (int)$market['demand_score'] ?>/100)</dd><dt>Kwaliteit</dt><dd><?= h($market['quality_label']) ?></dd><dt>WTB offers</dt><dd><?= (int)$market['buy_offers'] ?></dd><dt>WTS offers</dt><dd><?= (int)$market['sell_offers'] ?></dd><dt>Unieke traders</dt><dd><?= (int)$market['unique_traders'] ?></dd><dt>Mediaan WTB</dt><dd><?= h($money->ecto($market['median_wtb_ecto']!==null?(float)$market['median_wtb_ecto']:null)) ?></dd><dt>Mediaan WTS</dt><dd><?= h($money->ecto($market['median_wts_ecto']!==null?(float)$market['median_wts_ecto']:null)) ?></dd><dt>Laatste activiteit</dt><dd><?= h($market['last_activity'] ?? '—') ?></dd><dt>Herberekend</dt><dd><?= h($market['updated_at']) ?></dd></dl></div></aside></div>
<section class="panel" style="margin-top:16px"><h2>Actieve advertenties van exact deze variant</h2><div class="offers"><div class="row header"><span>Type</span><span>Trader / datum</span><span>Prijs</span><span>Basis</span><span>Details</span><span>Originele tekst</span></div><?php if(!$offers): ?><div class="empty">Geen actieve geaccepteerde advertenties.</div><?php endif; ?><?php foreach($offers as $o): ?><div class="row"><div class="<?= h($o['trade_type']) ?>"><?= strtoupper(h($o['trade_type'])) ?></div><div><strong><?= h($o['player']) ?></strong><br><span class="muted"><?= h($o['posted_at']) ?></span></div><div><strong><?= h($money->ecto($o['unit_price_ecto']!==null?(float)$o['unit_price_ecto']:null)) ?></strong><br><span class="muted"><?= h($money->armbrace($o['unit_price_ecto']!==null?(float)$o['unit_price_ecto']:null)) ?></span></div><div><?= h($o['price_basis'] ?? '—') ?><?php if((int)($o['quantity']??0)>1): ?><br><span class="muted">qty <?= (int)$o['quantity'] ?></span><?php endif; ?></div><div><?= h(trim(implode(' · ',array_filter([$o['requirement']!==null?'q'.$o['requirement']:null,$o['attribute_name']??null,(int)$o['is_oldschool']===1?'OS':null,(int)$o['is_inscribable']===1?'insc':null,mods($o['mods_json'])!=='—'?mods($o['mods_json']):null])))) ?: '—' ?></div><div><?= h($o['raw_segment'] ?: $o['message']) ?></div></div><?php endforeach; ?></div></section></main>
<script>const data=<?= json_encode($chart,JSON_UNESCAPED_SLASHES) ?>;const svg=document.getElementById('chart');if(!data.length){svg.innerHTML='<text x="450" y="130" text-anchor="middle" fill="#9ba8ba">Nog onvoldoende snapshots</text>';}else{const vals=data.flatMap(x=>[x.b,x.s]).filter(x=>x!==null&&x>0);if(!vals.length){svg.innerHTML='<text x="450" y="130" text-anchor="middle" fill="#9ba8ba">Snapshots bevatten nog geen prijzen</text>';}else{const min=Math.min(...vals),max=Math.max(...vals),range=Math.max(.01,max-min),W=900,H=260,p=18;function path(k){const pts=data.map((x,i)=>{const v=x[k];if(v===null||v<=0)return null;const px=p+(i/Math.max(1,data.length-1))*(W-p*2);const py=H-p-((v-min)/range)*(H-p*2);return[px,py]}).filter(Boolean);return pts.map((q,i)=>(i?'L':'M')+q[0].toFixed(1)+' '+q[1].toFixed(1)).join(' ')}svg.innerHTML='<line x1="18" y1="242" x2="882" y2="242" stroke="#293547"/><path d="'+path('b')+'" fill="none" stroke="#68d9a3" stroke-width="3"/><path d="'+path('s')+'" fill="none" stroke="#ef9090" stroke-width="3"/><text x="20" y="16" fill="#9ba8ba">'+max.toFixed(2)+'e</text><text x="20" y="254" fill="#9ba8ba">'+min.toFixed(2)+'e</text>';}}</script></body></html>
