<?php declare(strict_types=1);
$condition=static fn(string $type):string=>match($type){'wts_below'=>'WTS onder','wtb_above'=>'WTB boven','spread_above'=>'Spread boven','new_offer'=>'Nieuwe activiteit',default=>$type};
?>
<section class="page-intro"><div><span class="kicker">PERSOONLIJK</span><h1>Prijsalerts</h1><p>Alerts gaan alleen af bij een nieuwe overgang of nieuwe marktactiviteit, zodat je niet steeds dezelfde melding krijgt.</p></div><div class="actions"><a href="/watchlist">Watchlist</a><span class="badge <?=$unread>0?'sell':'trade'?>"><?=$unread?> ongelezen</span></div></section>
<?php if($error):?><div class="surface" style="border-color:rgba(239,106,103,.55)"><?=h($error)?></div><?php endif;?>
<?php if($result):?><div class="surface" style="border-color:rgba(81,199,141,.45)"><?=(int)$result['checked']?> gecontroleerd · <?=(int)$result['triggered']?> nieuwe events · <?=(int)$result['reset']?> gereset</div><?php endif;?>
<div class="grid"><section class="surface"><div class="section-heading"><div><span class="kicker">NIEUW</span><h2>Losse alert</h2></div></div><form method="post" action="/alerts" class="formgrid">
<label class="wide">Label<input name="label" placeholder="Naam voor deze alert"></label><label class="wide">Marktvariant<input name="market_key" list="alert-markets" required placeholder="Zoek of plak een market_key"></label><datalist id="alert-markets"><?php foreach($markets as $market):?><option value="<?=h($market['market_key'])?>"><?=h($market['item'])?></option><?php endforeach;?></datalist>
<label>Conditie<select name="condition_type"><option value="wts_below">WTS onder drempel</option><option value="wtb_above">WTB boven drempel</option><option value="spread_above">Spread boven drempel</option><option value="new_offer">Nieuwe marktactiviteit</option></select></label><label>Drempel<input name="threshold_ecto" inputmode="decimal" placeholder="Ecto; leeg bij activiteit"></label><div class="wide"><button class="btn">Alert opslaan</button></div></form></section>
<section class="surface"><div class="section-heading"><div><span class="kicker">ACTIES</span><h2>Controle</h2></div></div><div class="actions"><form method="post" action="/alerts"><input type="hidden" name="action" value="evaluate"><button class="btn">Nu controleren</button></form><form method="post" action="/alerts"><input type="hidden" name="action" value="read_all"><button class="btn secondary">Alles gelezen</button></form></div><p class="muted">Automatische controles blijven via de alert-cronjob lopen.</p></section></div>
<section class="surface"><div class="section-heading"><div><span class="kicker">INSTELLINGEN</span><h2>Mijn alerts</h2></div><span class="muted"><?=count($alerts)?> alerts</span></div><div class="tablewrap"><table><thead><tr><th>Alert</th><th>Conditie</th><th>Status</th><th>Doel</th><th>Acties</th></tr></thead><tbody>
<?php if($alerts===[]):?><tr><td colspan="5" class="muted">Nog geen alerts ingesteld.</td></tr><?php endif;?>
<?php foreach($alerts as $row):?><tr><td><strong><?=h($row['label']!==''?$row['label']:($row['item']??$row['market_key']))?></strong><small class="muted" style="display:block"><?=h($row['market_key'])?> · <?=h($row['source'])?></small></td><td><?=h($condition((string)$row['condition_type']))?><?=$row['threshold_ecto']!==null?' '.h($money->ecto((float)$row['threshold_ecto'])):''?></td><td><span class="badge <?=(int)$row['is_enabled']===1?'buy':'trade'?>"><?=(int)$row['is_enabled']===1?'Actief':'Pauze'?></span></td><td><span class="badge <?=(int)$row['condition_met']===1?'sell':'trade'?>"><?=(int)$row['condition_met']===1?'Geraakt':'Wachten'?></span></td><td><div class="actions"><form method="post" action="/alerts"><input type="hidden" name="action" value="toggle"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><button class="btn secondary">Toggle</button></form><form method="post" action="/alerts"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$row['id']?>"><button class="btn secondary">Wissen</button></form></div></td></tr><?php endforeach;?></tbody></table></div></section>
<section class="surface"><div class="section-heading"><div><span class="kicker">EVENTS</span><h2>Recente meldingen</h2></div></div><div class="tablewrap"><table><thead><tr><th>Melding</th><th>Moment</th><th></th></tr></thead><tbody><?php if($events===[]):?><tr><td colspan="3" class="muted">Nog niets getriggerd.</td></tr><?php endif;?><?php foreach($events as $event):?><tr style="<?=(int)$event['is_read']===0?'background:rgba(202,169,91,.05)':''?>"><td><strong><?=h($event['message'])?></strong><small class="muted" style="display:block"><?=h($event['market_key'])?></small></td><td><?=h($event['created_at'])?></td><td><?php if((int)$event['is_read']===0):?><form method="post" action="/alerts"><input type="hidden" name="action" value="read"><input type="hidden" name="event_id" value="<?=(int)$event['id']?>"><button class="btn secondary">Gelezen</button></form><?php endif;?></td></tr><?php endforeach;?></tbody></table></div></section>
