<?php
declare(strict_types=1);$root=dirname(__DIR__,3);require $root.'/bootstrap.php';$fail=0;function c16(bool $ok,string $l):void{global $fail;echo($ok?'OK   ':'FAIL ').$l.PHP_EOL;if(!$ok)$fail++;}
$g=new \LittyWatch\Market\Phase7E16MarketSemanticGuard(db());
foreach([['FMN (5)','fmn-5','Forget Me Not!'],['Japan','japan','Japan 1st Anniversary Shield'],['SP +5 (Sycthe)','sp-5-sycthe','Scythe Grip of the Ritualist'],['Cup','cup','Cup of the Bison'],['Luna 15e each','luna','Lunar Fortune'],['5 GooT 10e','goot','Gift of the Traveler'],['40 Stalk','stalk',"Stalker's Ration"],['Grail Stacks','grail-stacks','Grail of Holy Might'],['Saph','saph','Sapphire'],['WARSUPPLYS','warsupplys','War Supplies'],['Desroyer Cores / 1Kea','desroyer-cores-1kea','Destroyer Core']] as [$seg,$key,$exp]){$o=$g->repair(['item'=>$seg,'item_key'=>$key,'raw_segment'=>$seg,'quality_status'=>'review','quality_reason'=>'catalog_first_unresolved']);c16(($o['item']??'')===$exp,$seg.' => '.$exp);} 
$o=$g->repair(['item'=>'Miniature Greased Lightning','item_key'=>'miniature-greased-lightning','raw_segment'=>'Earth, lightning, blunt','quality_status'=>'review','quality_reason'=>'miniature_variant_unresolved']);c16(($o['quality_reason']??'')==='modifier_fragment_unresolved','Lightning false miniature blocked');
$o=$g->repair(['item'=>'Blessing of War','item_key'=>'blessing-of-war','raw_segment'=>'Bow -','quality_status'=>'review','quality_reason'=>'low_confidence']);c16(($o['quality_reason']??'')==='modifier_fragment_unresolved','Bow false Blessing blocked');
$sem=file_get_contents($root.'/app/Parser/SemanticNormalizer.php');c16(str_contains((string)$sem,'LITTYWATCH_PHASE7E16_ELITE_TOME_LISTS'),'Elite Tome list marker');c16(str_contains((string)$sem,'Forget Me Not!'),'FMN replacement');
$writer=file_get_contents($root.'/app/Market/StructuredOfferWriter.php');c16(str_contains((string)$writer,'LITTYWATCH_PHASE7E16_PREINSERT_MARKET_SEMANTICS'),'writer marker');
if($fail){echo "Phase 7E.16 smoke-test: {$fail} fout(en).\n";exit(1);}echo "Phase 7E.16 smoke-test volledig OK.\nDaarna reset-live-market; geen reparse-all.\n";
