<?php declare(strict_types=1);$k=$knowledge;$total=(int)($qualityStats['total']??0);$pct=static fn($n)=>$total?number_format(((int)$n/$total)*100,1,',','.').'%' :'0%';?>
<section class="page-intro"><div><span class="kicker">PARSER LEARNING</span><h1>Parser Review</h1><p>Controleer twijfelgevallen en leer LittyWatch nieuwe markttermen.</p></div><div class="actions"><a class="btn secondary" href="/parser-review/export">Export cases</a></div></section>
<?php if($message):?><div class="flash success"><?=h($message)?></div><?php endif;?>
<section class="stats-grid"><article><span>Berichten</span><strong><?=number_format($total,0,',','.')?></strong></article><article><span>Herkend</span><strong><?=$pct($qualityStats['parsed']??0)?></strong></article><article><span>Review</span><strong><?=$pct($qualityStats['review']??0)?></strong></article><article><span>Uitgesloten</span><strong><?=$pct($qualityStats['excluded']??0)?></strong></article></section>
<div class="review-layout"><section class="surface"><div class="top"><div><span class="kicker">QUEUE</span><h2><?=h(ucfirst($status))?> (<?=(int)($summary[$status]??0)?>)</h2></div><form class="filters"><select name="status"><?php foreach(['pending','approved','corrected','rejected']as$v):?><option <?=$status===$v?'selected':''?>><?=h($v)?></option><?php endforeach;?></select><input name="q" value="<?=h($query)?>" placeholder="Zoek bericht of item"><button class="btn">Filter</button></form></div><div class="review-list">
<?php if(!$rows):?><div class="empty-inline">Geen reviewregels gevonden.</div><?php endif;?>
<?php foreach($rows as$r):$expected=json_decode((string)($r['expected_json']??''),true)?:[];?><article class="review-card"><header><div><strong><?=h($r['player'])?></strong><small><?=h($r['posted_at'])?></small></div><span class="parse-status review"><?=number_format((float)$r['confidence']*100,0)?>% · <?=h($r['quality_reason'])?></span></header><blockquote><?=h($r['message'])?></blockquote><div class="review-proposals"><span>Parser: <strong><?=h($r['item'])?></strong></span><span>Markt: <?=h($r['market_key'])?></span><span>Segment: <?=h($r['raw_segment'])?></span></div><form method="post" class="review-edit"><input type="hidden" name="action" value="review"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><input type="hidden" name="return_status" value="<?=h($status)?>"><label>Status<select name="review_status"><?php foreach(['pending','approved','corrected','rejected']as$v):?><option <?=$r['review_status']===$v?'selected':''?>><?=h($v)?></option><?php endforeach;?></select></label><label>Correct item<input name="expected_item" value="<?=h($expected['item']??'')?>"></label><label>Alias leren<input name="alias" placeholder="obby edge"></label><label>Requirement<input name="expected_requirement" type="number" value="<?=h($expected['requirement']??'')?>"></label><label>Attribuut<input name="expected_attribute" value="<?=h($expected['attribute']??'')?>"></label><label>Market key<input name="expected_market_key" value="<?=h($expected['market_key']??'')?>"></label><label class="wide">Notitie / uitsluitingszin<input name="notes" value="<?=h($r['notes']??'')?>"></label><button class="btn">Opslaan en leren</button></form></article><?php endforeach;?></div></section>
<aside class="review-sidebar"><section class="surface"><span class="kicker">GEMISTE TERMEN</span><h2>Veel voorkomend</h2><div class="term-cloud"><?php foreach($terms as$t):?><span><?=h($t['term'])?> <strong><?=(int)$t['count']?></strong></span><?php endforeach;?></div></section>
<section class="surface"><span class="kicker">ALIAS</span><form method="post" class="stack-form"><input type="hidden" name="action" value="add_alias"><label>Alias<input name="alias" required></label><label>Item<input name="item_name" required></label><button class="btn">Toevoegen</button></form><div class="knowledge-list"><?php foreach($k['aliases']as$r):?><form method="post"><input type="hidden" name="action" value="delete_alias"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><span><strong><?=h($r['alias'])?></strong> → <?=h($r['item_name'])?></span><button class="icon-button">×</button></form><?php endforeach;?></div></section>
<section class="surface"><span class="kicker">UITSLUITING</span><form method="post" class="stack-form"><input type="hidden" name="action" value="add_exclusion"><label>Zin<input name="phrase" required></label><label>Type<select name="kind"><option value="noise">Noise</option><option value="service">Service</option><option value="character_name_sale">Naamverkoop</option></select></label><button class="btn">Toevoegen</button></form><div class="knowledge-list"><?php foreach($k['exclusions']as$r):?><form method="post"><input type="hidden" name="action" value="delete_exclusion"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><span><strong><?=h($r['phrase'])?></strong> · <?=h($r['kind'])?></span><button class="icon-button">×</button></form><?php endforeach;?></div></section>
<section class="surface"><span class="kicker">SETGROOTTE</span><form method="post" class="stack-form"><input type="hidden" name="action" value="add_set_size"><label>Item<input name="item_name" required></label><label>Aantal<input name="set_size" type="number" min="1" required></label><button class="btn">Toevoegen</button></form><div class="knowledge-list"><?php foreach($k['set_sizes']as$r):?><form method="post"><input type="hidden" name="action" value="delete_set_size"><input type="hidden" name="id" value="<?=(int)$r['id']?>"><span><strong><?=h($r['item_name'])?></strong> = <?=h($r['set_size'])?></span><button class="icon-button">×</button></form><?php endforeach;?></div></section></aside></div>
