<?php
declare(strict_types=1);
$root=dirname(__DIR__,3);
require $root.'/bootstrap.php';

$target=$root.'/app/Market/Phase7E21AcceptedSafetyGuard.php';
$writer=$root.'/app/Market/StructuredOfferWriter.php';

if(!is_file($writer)){fwrite(STDERR,"ERROR: StructuredOfferWriter.php ontbreekt.\n");exit(1);}

$backup=$root.'/storage/backups/phase7e21-fix2-'.date('Ymd-His');
@mkdir($backup,0775,true);
copy($writer,$backup.'/StructuredOfferWriter.php');
if(is_file($target)) copy($target,$backup.'/Phase7E21AcceptedSafetyGuard.php');

$guard=base64_decode('PD9waHAKZGVjbGFyZShzdHJpY3RfdHlwZXM9MSk7CgpuYW1lc3BhY2UgTGl0dHlXYXRjaFxNYXJrZXQ7CgpmaW5hbCBjbGFzcyBQaGFzZTdFMjFBY2NlcHRlZFNhZmV0eUd1YXJkCnsKICAgIHB1YmxpYyBmdW5jdGlvbiByZXBhaXIoYXJyYXkgJHJvdyk6IGFycmF5CiAgICB7CiAgICAgICAgJGtleSA9IHN0cl9yZXBsYWNlKCdfJywnLScsbWJfc3RydG9sb3dlcih0cmltKChzdHJpbmcpKCRyb3dbJ2l0ZW1fa2V5J10gPz8gJycpKSkpOwogICAgICAgICRpdGVtID0gbWJfc3RydG9sb3dlcih0cmltKChzdHJpbmcpKCRyb3dbJ2l0ZW0nXSA/PyAnJykpKTsKICAgICAgICAkc2VnID0gbWJfc3RydG9sb3dlcih0cmltKChzdHJpbmcpKCRyb3dbJ3Jhd19zZWdtZW50J10gPz8gJycpKSk7CiAgICAgICAgJG1zZyA9IG1iX3N0cnRvbG93ZXIoKHN0cmluZykoJHJvd1snX21lc3NhZ2UnXSA/PyAnJykpOwoKICAgICAgICBpZiAoc3RyX2NvbnRhaW5zKCRrZXksICdzdGFmZicpICYmIHByZWdfbWF0Y2goJy9cXGJzY2VwdGVyXFxiL2l1JywgJHNlZykgJiYgIXByZWdfbWF0Y2goJy9cXGJzdGFmZlxcYi9pdScsICRzZWcpKSB7CiAgICAgICAgICAgIGlmIChwcmVnX21hdGNoKCcvXFxiZnJvZ2c/eT9cXGJ8XFxiZnJvZ1xcYi9pdScsICRtc2cpKSB7CiAgICAgICAgICAgICAgICAkcm93WydpdGVtJ109J0Zyb2cgU2NlcHRlcic7CiAgICAgICAgICAgICAgICAkcm93WydpdGVtX2tleSddPSdmcm9nLXNjZXB0ZXInOwogICAgICAgICAgICAgICAgJHJvd1snbWFya2V0X2tleSddPSdmcm9nLXNjZXB0ZXInOwogICAgICAgICAgICAgICAgJHJvd1sncXVhbGl0eV9zdGF0dXMnXT0nYWNjZXB0ZWQnOwogICAgICAgICAgICAgICAgJHJvd1sncXVhbGl0eV9yZWFzb24nXT0nY2F0YWxvZ19tYXRjaCc7CiAgICAgICAgICAgICAgICAkcm93Wydjb25maWRlbmNlJ109bWF4KChmbG9hdCkoJHJvd1snY29uZmlkZW5jZSddPz8wKSwwLjk2KTsKICAgICAgICAgICAgICAgIHJldHVybiAkcm93OwogICAgICAgICAgICB9CiAgICAgICAgICAgIHJldHVybiAkdGhpcy0+cmVqZWN0KCRyb3csJ2FjY2VwdGVkX3dlYXBvbl90eXBlX2NvbGxpc2lvbicsMC4yMCk7CiAgICAgICAgfQoKICAgICAgICBpZiAocHJlZ19tYXRjaCgnL1xcYndhbmRcXGIvaXUnLCRzZWcpICYmICgKICAgICAgICAgICAgc3RyX2NvbnRhaW5zKCRrZXksJ2NoYWtyYW0nKSB8fCBzdHJfY29udGFpbnMoJGl0ZW0sJ2NoYWtyYW0nKSB8fAogICAgICAgICAgICBzdHJfY29udGFpbnMoJGtleSwnZm9jdXMnKSB8fCBzdHJfY29udGFpbnMoJGl0ZW0sJ2ZvY3VzJykKICAgICAgICApKSByZXR1cm4gJHRoaXMtPnJlamVjdCgkcm93LCdhY2NlcHRlZF93ZWFwb25fdHlwZV9jb2xsaXNpb24nLDAuMjApOwoKICAgICAgICBpZiAoJGtleT09PSdvZi1lbmNoYW50aW5nJyAmJiBwcmVnX21hdGNoKCcvXFxiMTVcXHMqJVxccyooPzplbmNofGVuY2hhbnRlZClcXGIvaXUnLCRzZWcpKQogICAgICAgICAgICByZXR1cm4gJHRoaXMtPnJlamVjdCgkcm93LCdhY2NlcHRlZF9tb2RpZmllcl9jb2xsaXNpb24nLDAuMjApOwoKICAgICAgICBpZiAoJGtleT09PSdibGVzc2luZy1vZi13YXInICYmIHByZWdfbWF0Y2goJy9cXGJib3dcXGIvaXUnLCRzZWcpICYmICFwcmVnX21hdGNoKCcvXFxiYmxlc3NpbmdcXHMrb2ZcXHMrd2FyXFxiL2l1Jywkc2VnKSkKICAgICAgICAgICAgcmV0dXJuICR0aGlzLT5yZWplY3QoJHJvdywnYWNjZXB0ZWRfbmFtZWRfaXRlbV9jb2xsaXNpb24nLDAuMjApOwoKICAgICAgICBpZiAoc3RyX2NvbnRhaW5zKCRrZXksJ3J1bmUnKSAmJiBwcmVnX21hdGNoKCcvXFxic2hpZSg/OmxkKT9cXGIvaXUnLCRzZWcuJyAnLiRtc2cpKQogICAgICAgICAgICByZXR1cm4gJHRoaXMtPnJlamVjdCgkcm93LCdhY2NlcHRlZF9pdGVtX2ZhbWlseV9jb2xsaXNpb24nLDAuMjApOwoKICAgICAgICBpZiAoaW5fYXJyYXkoJGtleSxbJ2ZpZXJ5JywnZmlyZScsJ2ZpZXJ5LWRyYWcnXSx0cnVlKSAmJiBwcmVnX21hdGNoKCcvXFxiZmllcnlcXHMrZHJhZyg/Om9uKT9cXHMrc3dvcmRcXGIvaXUnLCRzZWcuJyAnLiRtc2cpKSB7CiAgICAgICAgICAgICRyb3dbJ2l0ZW0nXT0nRmllcnkgRHJhZ29uIFN3b3JkJzsKICAgICAgICAgICAgJHJvd1snaXRlbV9rZXknXT0nZmllcnktZHJhZ29uLXN3b3JkJzsKICAgICAgICAgICAgJHJvd1snbWFya2V0X2tleSddPSdmaWVyeS1kcmFnb24tc3dvcmQnOwogICAgICAgICAgICAkcm93WydxdWFsaXR5X3N0YXR1cyddPSdhY2NlcHRlZCc7CiAgICAgICAgICAgICRyb3dbJ3F1YWxpdHlfcmVhc29uJ109J2NhdGFsb2dfbWF0Y2gnOwogICAgICAgICAgICAkcm93Wydjb25maWRlbmNlJ109bWF4KChmbG9hdCkoJHJvd1snY29uZmlkZW5jZSddPz8wKSwwLjk2KTsKICAgICAgICAgICAgcmV0dXJuICRyb3c7CiAgICAgICAgfQoKICAgICAgICBpZiAoc3RyX2NvbnRhaW5zKCRrZXksJ3NoaWVsZCcpIHx8IHN0cl9jb250YWlucygkaXRlbSwnc2hpZWxkJykgfHwgcHJlZ19tYXRjaCgnL1xcYnNoaWVsZFxcYi9pdScsJHNlZykpIHsKICAgICAgICAgICAgJHJlcT0kdGhpcy0+ZXh0cmFjdFNoaWVsZFJlcXVpcmVtZW50KCRzZWcpOwogICAgICAgICAgICBpZigkcmVxIT09bnVsbCl7CiAgICAgICAgICAgICAgICAkcm93WydhdHRyaWJ1dGVfa2V5J109JHJlcVsna2V5J107CiAgICAgICAgICAgICAgICAkcm93WydhdHRyaWJ1dGVfbmFtZSddPSRyZXFbJ25hbWUnXTsKICAgICAgICAgICAgfQogICAgICAgIH0KCiAgICAgICAgcmV0dXJuICRyb3c7CiAgICB9CgogICAgcHJpdmF0ZSBmdW5jdGlvbiBleHRyYWN0U2hpZWxkUmVxdWlyZW1lbnQoc3RyaW5nICRzZWdtZW50KTogP2FycmF5CiAgICB7CiAgICAgICAgaWYoIXByZWdfbWF0Y2goJy9cXGIoPzpxfHJ8cmVxKVxccypcXGR7MSwyfVxccyoodGFjKD86dGljcyk/fHN0cig/OmVuZ3RoKT98Y29tbWFuZHxjb21tfG1vdCg/Oml2YXRpb24pPylcXGIvaXUnLCRzZWdtZW50LCRtKSkKICAgICAgICAgICAgcmV0dXJuIG51bGw7CgogICAgICAgICR0PW1iX3N0cnRvbG93ZXIoJG1bMV0pOwogICAgICAgIGlmKHN0cl9zdGFydHNfd2l0aCgkdCwndGFjJykpIHJldHVybiBbJ2tleSc9Pid0YWN0aWNzJywnbmFtZSc9PidUYWN0aWNzJ107CiAgICAgICAgaWYoc3RyX3N0YXJ0c193aXRoKCR0LCdzdHInKSkgcmV0dXJuIFsna2V5Jz0+J3N0cmVuZ3RoJywnbmFtZSc9PidTdHJlbmd0aCddOwogICAgICAgIGlmKCR0PT09J2NvbW1hbmQnfHwkdD09PSdjb21tJykgcmV0dXJuIFsna2V5Jz0+J2NvbW1hbmQnLCduYW1lJz0+J0NvbW1hbmQnXTsKICAgICAgICBpZihzdHJfc3RhcnRzX3dpdGgoJHQsJ21vdCcpKSByZXR1cm4gWydrZXknPT4nbW90aXZhdGlvbicsJ25hbWUnPT4nTW90aXZhdGlvbiddOwogICAgICAgIHJldHVybiBudWxsOwogICAgfQoKICAgIHByaXZhdGUgZnVuY3Rpb24gcmVqZWN0KGFycmF5ICRyb3csc3RyaW5nICRyZWFzb24sZmxvYXQgJGNhcCk6YXJyYXkKICAgIHsKICAgICAgICAkcm93WydxdWFsaXR5X3N0YXR1cyddPSdyZWplY3RlZCc7CiAgICAgICAgJHJvd1sncXVhbGl0eV9yZWFzb24nXT0kcmVhc29uOwogICAgICAgICRyb3dbJ2NvbmZpZGVuY2UnXT1taW4oKGZsb2F0KSgkcm93Wydjb25maWRlbmNlJ10/PzApLCRjYXApOwogICAgICAgIHJldHVybiAkcm93OwogICAgfQp9Cg==');
if($guard===false || file_put_contents($target,$guard)===false){
    fwrite(STDERR,"ERROR: FIX2 guard kon niet worden geschreven.\n");exit(1);
}

$writerCode=file_get_contents($writer);
if(!str_contains((string)$writerCode,'LITTYWATCH_PHASE7E21_ACCEPTED_SAFETY')){
    fwrite(STDERR,"ERROR: 7E.21 writer marker ontbreekt.\n");exit(1);
}

echo "OK: LittyWatch V5.2 Phase 7E.21 FIX2 geïnstalleerd.\n";
echo "Backup: {$backup}\n";
echo "Draai nu:\n";
echo "  php -l app/Market/Phase7E21AcceptedSafetyGuard.php\n";
echo "  php -l app/Market/StructuredOfferWriter.php\n";
echo "  php tools/maintenance/phase7e21-fix2/smoke-test.php\n";
