<?php
declare(strict_types=1);
namespace LittyWatch\Repositories;
use PDO;
final class PlatformRepository{
 public function __construct(private readonly PDO $pdo){}
 public function tableExists(string $name):bool{$s=$this->pdo->prepare("SELECT 1 FROM sqlite_master WHERE type='table' AND name=:n");$s->execute([':n'=>$name]);return(bool)$s->fetchColumn();}
 public function counts():array{$map=['messages','offers','structured_offers','market_intelligence','watchlist','alerts','alert_events','item_assets'];$out=[];foreach($map as$t){$out[$t]=$this->tableExists($t)?(int)$this->pdo->query('SELECT COUNT(*) FROM '.$t)->fetchColumn():0;}return$out;}
 public function live(int $limit=150):array{if(!$this->tableExists('messages'))return[];$sql="SELECT id,player,message,posted_at FROM messages ORDER BY id DESC LIMIT ".max(1,min(500,$limit));return$this->pdo->query($sql)->fetchAll();}
 public function traders(string $query='',int $limit=250):array{if(!$this->tableExists('messages'))return[];$where=$query!==''?'WHERE player LIKE :q':'';$sql="SELECT player,COUNT(*) messages,MAX(posted_at) last_seen FROM messages $where GROUP BY player ORDER BY messages DESC,last_seen DESC LIMIT ".max(1,min(500,$limit));$s=$this->pdo->prepare($sql);if($query!=='')$s->execute([':q'=>'%'.$query.'%']);else$s->execute();return$s->fetchAll();}
 public function trader(string $name,int $limit=200):array{if(!$this->tableExists('messages'))return['summary'=>null,'messages'=>[],'offers'=>[]];$s=$this->pdo->prepare('SELECT player,COUNT(*) messages,MIN(posted_at) first_seen,MAX(posted_at) last_seen FROM messages WHERE player=:p GROUP BY player');$s->execute([':p'=>$name]);$summary=$s->fetch()?:null;$s=$this->pdo->prepare('SELECT id,player,message,posted_at FROM messages WHERE player=:p ORDER BY id DESC LIMIT '.max(1,min(500,$limit)));$s->execute([':p'=>$name]);$messages=$s->fetchAll();$offers=[];if($this->tableExists('structured_offers')){$s=$this->pdo->prepare("SELECT so.*,m.posted_at FROM structured_offers so JOIN messages m ON m.id=so.message_id WHERE m.player=:p ORDER BY so.id DESC LIMIT 200");$s->execute([':p'=>$name]);$offers=$s->fetchAll();}return compact('summary','messages','offers');}
 public function trends(int $limit=100):array{if(!$this->tableExists('market_intelligence'))return[];$sql="SELECT * FROM market_intelligence ORDER BY CASE WHEN last_activity IS NULL THEN 1 ELSE 0 END,last_activity DESC LIMIT ".max(1,min(500,$limit));return$this->pdo->query($sql)->fetchAll();}
 public function intelligence(string $query='',int $limit=250):array{if(!$this->tableExists('market_intelligence'))return[];$where=$query!==''?'WHERE item LIKE :q OR market_key LIKE :q':'';$sql="SELECT * FROM market_intelligence $where ORDER BY COALESCE(deal_score,0) DESC,COALESCE(confidence_score,0) DESC LIMIT ".max(1,min(500,$limit));$s=$this->pdo->prepare($sql);$query!==''?$s->execute([':q'=>'%'.$query.'%']):$s->execute();return$s->fetchAll();}
 public function latestTimes():array{$out=[];foreach(['messages'=>'posted_at','market_intelligence'=>'last_activity','alert_events'=>'created_at','asset_imports'=>'created_at'] as$t=>$c){$out[$t]=$this->tableExists($t)?$this->pdo->query("SELECT MAX($c) FROM $t")->fetchColumn():null;}return$out;}
 public function dbInfo():array{$path=(string)$this->pdo->query('PRAGMA database_list')->fetch()['file'];return['path'=>$path,'bytes'=>is_file($path)?filesize($path):0,'journal'=>$this->pdo->query('PRAGMA journal_mode')->fetchColumn(),'version'=>$this->pdo->query('SELECT sqlite_version()')->fetchColumn()];}
}
